sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: SsSTl8P2LsKupDNymFnWPbxkc8X3ksAWCnrSGElASf0xntEntpJAeOa60eJ+aXuXNGA2VBC7RPsEBZMpzWrsGuqIkcXo65ZTZU6WSf+FXSteyCQ8g5C6hFiahebx0Zfc5Gs/8L5bgZWojiEYFA9qGZ/dvHIhdZUwbXdKr6/7kNbQPmewsoAVPVisrQUuL/PXzbXTMM0GIqVE1xOvxJ4Vrb/j8TDid3aLeYbUbAfk9K7/rnaY1/lKsJObBW+fj6Ndrc31Lvj9RDLvDCyCB//I7H3Iy5xB+jI08qmxQaZMCiaQP7lv4Nwm/GRlzQXDDYbY2LOlwL8UMbM3IPU53bjZJe7on37rn2rtXX4K6DeARHbdiVsrRRgOLkwXsPg+/WLLmz4U4UU6J0VDAhmb0KUioSUL99xgyayIw1pzSU/jzSrLl//JJsqMeV0n3PJEQYeaxyXK+omKmvC+u+7A0vpLY1xK4vgqFOHjvmz5HKvL7oUXqC04+iHCFMRZwD6O5y7XFbSQmgvKbrsofolFe6Liezla/uOHSasM742HczMr8u5FJcZ3holvFdhmaNjcZnKoyN7Jy9SBOuxCqP8M06i8d6wyVyfMFIf0g0Mgz0MNgD2p6Qz3ytN0jpaZiukv98hw9eQFuB2RGWIqnKRnCj+zcZA0OiyXD1e5xVei2Y7QqM8=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: R9OwKA/YhRa2GWFMzm6TD/5ytz0czemInBpTWLCKcaedzzR3mwc3aqbMZfZWs4JcF/1PnJJKFZJVa0eELmWhyHBiay5R4hePZ1AjCAKh2BXftQGP3b8rMHVI5SofnkeV992nMtTPKpMxZqoATQpfJ/kUxctKNqHylj6/NUOswhVnCnM/61wA2IxkjbmBQjAsHukDletuQmO6oIE15gnKQmzpaaZwqGfU/XT4hF1whC2EkNsss9wyTcLuV9SGMTh+K9eNKrJ+oLinNp5cseFHxyKComM8NaTxjIQ/+VG45HrFW9SQBwYc2wL3yx2NnK7hZo8djM+nWO0CrKt7vY3Oum8AThzfA7wfhGHlD213qgdIvwBh0DVKHy64Liftjv08RHr+GBbVzLyU74LNT6BLSO0pNZG3Ty9fiYAre7nrMjSHAl9nn4LjvYS7/dygatFVCcJ8oKw9rZsf4vqjN5H7sgK6huOpdgL2elStpWHzlM0Hfjhot9Yd2/SSrLKNE4LnwPvVtpCmmVQWbC/zHrW68PPHBRBVipnNympxBSVR4PpNApN3Ks65McSG+xv1u3JmlEundokKR+s11u4+xp4DgIJEnFOhqJHrKguEy2tuRMr0A9hdl03xtXzQZuAVJYPw7Q671/RCSyLSbLPuqBgo7mtgwIM6/zr9EAExRx2xWsU=
